CO=xfilip46-thesis-presentation

all:
	pdflatex -halt-on-error $(CO)
	pdflatex -halt-on-error $(CO)

clean:
	rm -f *.dvi *.log $(CO).blg $(CO).bbl $(CO).toc *.aux $(CO).out $(CO).lof $(CO).ptc $(CO).nav $(CO).snm
	rm -f $(CO).pdf
	rm -f *~
